# Generated by Django 2.1.7 on 2019-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_auto_20190430_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='r_token',
            field=models.BooleanField(default=False),
        ),
    ]
