# Generated by Django 2.1.7 on 2019-04-20 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
