# Generated by Django 2.1.7 on 2019-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_auto_20190502_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.TextField(blank=True),
        ),
    ]
